name: flutter_local_notifications_platform_interface
publish_to: none
description: A common platform interface for the flutter_local_notifications plugin.
version: 9.0.0
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_platform_interface
issue_tracker: https://github.com/MaikuB/flutter_local_notifications/issues

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
